pylint fixes
ElSnoMan/pyleniumio pull request #288
Opened 2022-10-20 22:06 UTC by marksmayo

Simplifying some statements / code blocks, fixing deprecated logging calls, and a couple of others.

2022-10-20 22:44 UTC, ElSnoMan commented on pylenium/element.py
> +        apply_style(f"border: {0}px solid {1};".format(border, color))
Either use an f-string or use .format()

2022-10-20 22:46 UTC, ElSnoMan requested changes
Thanks for cleaning things up and submitting a Pull Request! I have one small request, but otherwise, it all looks great! I just merged a branch to `main`, which you'll probably want to merge to this branch, but hopefully there are no conflicts

2022-10-21 00:30 UTC, marksmayo commented on pylenium/element.py
> +        apply_style(f"border: {0}px solid {1};".format(border, color))
fixed in latest commit post merge

2022-10-21 00:38 UTC, marksmayo commented
@ElSnoMan looks like your merge broke one test? test_element_actions.py, seems unable to find a file?

2022-10-21 02:36 UTC, ElSnoMan approved these changes

2022-10-21 02:48 UTC, merged

2022-10-21 02:52 UTC, ElSnoMan commented
> @ElSnoMan looks like your merge broke one test? test_element_actions.py, seems unable to find a file?

It's been resolved, so no worries. Your PR has been merged 🎉